name: todo_analytics

profile: todo_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["disabled"]

snapshots:
  todo_analytics:
    +meta:
      dagster:
        group: "snapshots"

models:
  todo_analytics:
    intermediate:
      +materialized: view
      +tags: "int"
    staging:
      +materialized: view
      +tags: "staging"
      +meta:
        dagster:
          group: "staging"
      base:
        # utilizing the strat to allow deleting completed data from src ticktick
        +tags: "base"
      metrics:
        +tags: "metrics"
        enabled: false
      
    marts:
      +meta:
        dagster:
          group: "marts"
      core:
        +materialized: table
        +tags: "core"
      metrics:
        +tags: "metrics"
        enabled: false

seeds:
  todo_analytics:
    +meta:
      dagster:
        group: "seeds"
    +full_refresh: true
    +tags: "seeds"
    list_goal_mapping:
      +column_types:
        goal_ids: "text"
    date_seed:
      full_refresh: false
        
vars:
    "dbt_date:time_zone": "Asia/Ho_Chi_Minh"
    # be used in model stg_dates_lookahead
    "lookahead_window": 90
