name: todo_analytics

profile: todo_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  todo_analytics:
    raw_source:
      # utilizing the strat to allow deleting completed data from src ticktick
      +tags: "raw"
    staging:
      +materialized: view
      +tags: "staging"
    marts:
      core:
        +materialized: table
        +tags: "core"
      metrics:
        +tags: "metrics"

seeds:
  todo_analytics:
    +full_refresh: true
    +tags: "seeds"
    list_goal_mapping:
      +column_types:
        goal_ids: "text"
    date_seed:
      full_refresh: false
        
vars:
    "dbt_date:time_zone": "Asia/Ho_Chi_Minh"
    # be used in model stg_dates_lookahead
    "lookahead_window": 90