todo_analytics:
  outputs:
    dev:
      type: postgres
      host: "{{env_var('DW_HOST')}}"
      port: 5433
      user: "{{env_var('DW_USER')}}"
      password: "{{env_var('DW_PASSWORD')}}"
      dbname: "{{env_var('DW_DBNAME')}}"
      schema: dev
      sslmode: disable
      threads: 12
    ci:
      type: postgres
      host: "{{env_var('DW_HOST')}}"
      port: 5433
      user: "{{env_var('DW_USER')}}"
      password: "{{env_var('DW_PASSWORD')}}"
      dbname: "{{env_var('DW_DBNAME')}}"
      schema: "{{var('schema_name', 'ci')}}"
      sslmode: disable
      threads: 12
    prod:
      type: postgres
      host: "{{env_var('DW_HOST')}}"
      port: 5433
      user: "{{env_var('DW_USER')}}"
      password: "{{env_var('DW_PASSWORD')}}"
      dbname: "{{env_var('DW_DBNAME')}}"
      schema: prod
      sslmode: disable
      threads: 12

  target: "{{env_var('TARGET_SCHEMA','dev')}}"