name: CI

on:
  pull_request:
  workflow_dispatch:
    


jobs:
  validate_dbt_models:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Set var CI_SCHEMA
        run: echo "CI_SCHEMA=PR_${{ github.event.number }}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-env
        with: 
          PROD_ENV: ${{ secrets.PROD_ENV }}           


      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          dbt deps

      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: dbt build models
        run: CI_SCHEMA=$CI_SCHEMA dbt build --target ci --exclude "validate_yaml_schema"
